#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Polar Wandering  # The title of the book. Will be placed in the left navbar.
author                      : Young CEED Team  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : book/logo.png  # A path to the book logo

execute:
  execute_notebooks: 'off'  # Eventually we want this to be 'on'.
  

# Binder support
repository:
  url                       : https://github.com/PolarWandering/Young_CEED  
  branch                    : main  
  
launch_buttons:
  notebook_interface: "jupyterlab"
  
launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/PolarWandering/Young_CEED.git/HEAD"  
  colab_url: "https://colab.research.google.com/github/PolarWandering/Young_CEED/blob/main/Preprocessing.ipynb" # just for one notebook for now


