#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Polar Wandering  # The title of the book. Will be placed in the left navbar.
author                      : Young CEED Team  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : book/logo.png  # A path to the book logo

execute:
  execute_notebooks: 'off'


